rt_music:
    resource: "@IUTCatalogBundle/Resources/config/routing.yml"
    prefix:   /

r_tapp:
    resource: "@IUTappBundle/Resources/config/routing.yml"
    prefix:   /

cart:
    resource: "@IUTUserBundle/Resources/config/routing.yml"
    prefix:   /cart/

login:
    pattern:   /login
    defaults:  { _controller: IUTUserBundle:Security:login }

login_check:
    pattern:   /login_check

logout:
    pattern:   /logout

signin:
    pattern:   /signin
    defaults:  { _controller: IUTUserBundle:Security:signin }




