rt_music:
    resource: "@IUTCatalogBundle/Resources/config/routing.yml"
    prefix:   /

r_tapp:
    resource: "@IUTappBundle/Resources/config/routing.yml"
    prefix:   /

login_check:
    pattern:   /login_check

login:
    pattern:   /login
    defaults:  { _controller: IUTUserBundle:Security:login }

logout:
    pattern:   /logout

signin:
    path:     /signin
    defaults:  { _controller: IUTUserBundle:Security:signin }

cart:
    resource: "@IUTUserBundle/Resources/config/routing.yml"
    prefix:   /cart/
