security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        in_memory:
            memory:
                users:
                    user:  { password: userpass, roles: [ 'ROLE_USER' ] }
                    admin: { password: adminpass, roles: [ 'ROLE_ADMIN' ] }

#        main:
#            entity: { class: IUTUserBundle:User, property: username }

    firewalls:

        dev:
                    pattern:  ^/(_(profiler|wdt)|css|images|js)/
                    security: false

        main_login:
            pattern:  ^/login$
            security: false



        main:
            pattern:   ^/
            anonymous: false
            provider : in_memory
            form_login:
                login_path:  login
                check_path:   login_check
            logout:
                path:   logout
                target: /home


    access_control:
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }