rt_music_homepage:
    path:     /musiciens/
    defaults: { _controller: IUTCatalogBundle:Musicien:index }

rt_music_musicienspage:
    path:     /musiciens/{page}
    defaults: { _controller: IUTCatalogBundle:Musicien:list }

rt_music_musicien_details_page:
    path:     /musicien/{id}
    defaults: { _controller: IUTCatalogBundle:Musicien:show }

rt_music_musicien_picture:
    path:     /musicien/picture/{id}
    defaults: { _controller: IUTCatalogBundle:Default:displayPicture }

rt_music_generatePicture:
    path:     /musicien/generatePicture/{class}/{id}
    defaults: { _controller: IUTCatalogBundle:Default:generatePicture }

rt_music_albums:
    path:     /albums/
    defaults: { _controller: IUTCatalogBundle:Album:index }

rt_music_album_details:
    path:     /album/{id}
    defaults: { _controller: IUTCatalogBundle:Album:show }

rt_test:
  path:       /test
  defaults:   { _controller: IUTCatalogBundle:Default:test }


catalog_disque_details:
    path:     /disque/{id}
    defaults: { _controller: IUTCatalogBundle:Disque:show }


catalog_genre_index:
    path:     /genres
    defaults: { _controller: IUTCatalogBundle:Genre:index }

catalog_genre_details:
    path:     /genre/{id}
    defaults: { _controller: IUTCatalogBundle:Genre:show }

catalog_instrument_index:
    path:     /instruments
    defaults: { _controller: IUTCatalogBundle:Instrument:index }

catalog_instrument_details:
    path:     /instrument/{id}
    defaults: { _controller: IUTCatalogBundle:Instrument:show }

catalog_oeuvre_index:
    path:     /oeuvres
    defaults: { _controller: IUTCatalogBundle:Oeuvre:index }

catalog_oeuvre_details:
    path:     /oeuvre/{id}
    defaults: { _controller: IUTCatalogBundle:Oeuvre:show }

catalog_musicien_composers:
    path:     /composers/
    defaults: { _controller: IUTCatalogBundle:Musicien:composers }

catalog_musicien_interpretes:
    path:     /interpretes/
    defaults: { _controller: IUTCatalogBundle:Musicien:interpretes }

catalog_musicien_chefsOrchestre:
    path:     /chefsOrchestres/
    defaults: { _controller: IUTCatalogBundle:Musicien:chefsOrchestre }