parameters:
#    rt_music.example.class: IUT\CatalogBundle\Example

services:
#    rt_music.example:
#        class: %rt_music.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
