r_tapp_homepage:
    path:     /home
    defaults: { _controller: RTappBundle:Default:index }

r_tapp_aboutpage:
    path:     /about
    defaults: { _controller: RTappBundle:Default:about }


r_tapp_testpage:
    path:     /test
    defaults: { _controller: RTappBundle:Default:test }