parameters:
#    iut_user.example.class: IUT\UserBundle\Example

services:
#    iut_user.example:
#        class: %iut_user.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
